{% set version = "0.0.4" %}

package:
  name: pangaea
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pangaea/pangaea-{{ version }}.tar.gz
  sha256: a114424e34e42befa691ddfe5f07272867f095fdc4f28dca633d5c6cadf26c16

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gazar
    - netcdf4
    - wrf-python

test:
  imports:
    - pangaea

about:
  home: https://github.com/snowman2/pangaea
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'An xarray extension for land surface models.'
  description: |
    An xarray extension for land surface models.
  doc_url: http://pangaea.readthedocs.io
  dev_url: https://github.com/snowman2/pangaea

extra:
  recipe-maintainers:
    - snowman2
    - swainn
    - mgeheran
