travis:
  secure:
    BINSTAR_TOKEN: eKz3OxW+MBcU37zWi/PAbkXLFtLFiCLVf29C9S2nVlY4ljeZa3+B4Sve3kMNyF69N1g/jcgpAec0z/G/Np/e0JClojFG7HuKcEqoOHIX7UBQIqXThPs6g9esbs2ccZGlJiik/xaWw8gPjtMFE4cOpYuNQGKM2VQScxQN85gyr63WTnX1UXAdyzQ9QnAActxLKGEFXassU+LsK/wzvtCXRSfqOhKmfR71T1a065lgBy3FI56FsM4ZTvXR5LWthx0ySh7zr6PPvOL5XFXUUWCift0vwaiSbQRFYGg2fNmn6PAIAePaE3IrQlyPMDuzXuhWgCNz2haLH/Apf8/XBAPb4e6YIPvfZ5JVsFhXJVG3BM1hjIVNQu5hiYPV4i9ULcyNhoU7jItZslDVf9csgHMamylVONcAb2HvJpr8rm3VlHOyfjZqP7YHvdJnCN/hL4HTopOaSeo/iqE56CrzPCV25j00hpUgSzpR71dfIWAm9nX9FG6bstYqNTTqsLvED4yR653Z7VtBytTOiKemfF6lLyqkfDpVz730dMBAl+euICy73ZyRosHYfh/s0neBoCdq/V/sigpPVdnA7IEfCQgRdsmrDQs3SsHeIiy135VXF108Pjse7AT4zf/WDCoHY/sWTyj/5oNVPmalXTyvqaLb6XXOvuFmoJBAVxKyYPaeKP0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
min_py_ver: '36'
